services:
  coredns:
    image: coredns-tailscale:latest
    container_name: coredns
    network_mode: host
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /opt/coredns-tailscale/Corefile:/etc/coredns/Corefile
    restart: unless-stopped
  
  portainer:
    image: portainer/portainer-ce:sts
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    restart: unless-stopped